apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::817928572948:role/dev-eks-auto-mode-3-secrets-store-csi-driver
  labels:
    app: eks-addons-testing
---
# Note: The Pod Identity association is already created via Terraform
# Association ID: a-veicnwctqitmupuqc
# Role ARN: arn:aws:iam::817928572948:role/dev-eks-auto-mode-3-secrets-store-csi-driver
