# Default values for flamecraft-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: public.ecr.aws/e9s5a3s2/flamecraft
  pullPolicy: Always
  tag: "19"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: "70m"
    memory: "70Mi"
  limits:
    cpu: "100m"
    memory: "100Mi"

namespace: dev

serviceAccount:
  create: false
  name: ""

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 70
  customMetrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 5

securityContext:
  runAsNonRoot: true
  runAsUser: 10000
  runAsGroup: 10000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

imagePullSecrets:
  - name: regcred

env:
  - name: FLASK_ENV
    value: production
  - name: TMPDIR
    value: /tmp

volumes:
  - name: tmp
    emptyDir: {}

volumeMounts:
  - name: tmp
    mountPath: /tmp

probes:
  livenessProbe:
    httpGet:
      path: /health
      port: 5500
    initialDelaySeconds: 10
    periodSeconds: 15
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /ready
      port: 5500
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
