apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-hello-friend.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "nginx-hello"
  template:
    metadata:
      labels:
        app: "nginx-hello"
    spec:
      containers:
        - name: nginx-hello
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80

