apiVersion: v1
kind: Service
metadata:
  name: service-nginx-hello
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: "nginx-hello"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}

