apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-irsa-deployment
  labels:
    app: nginx-irsa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-irsa
  template:
    metadata:
      labels:
        app: nginx-irsa
    spec:
      serviceAccountName: nginx-irsa-deployment-sa
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "nginx-irsa-deployment-aws-secrets"
      containers:
      - name: nginx-irsa-deployment
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-irsa-deployment
  labels:
    app: nginx-irsa
spec:
  selector:
    app: nginx-irsa
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
