apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-test-pod-identity
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "test-secret"
        objectType: "secretsmanager"
    region: ap-south-1
    usePodIdentity: "true"
